language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
services:
  - redis-server
before_install:
  - mkdir -p $HOME/buildout-cache/{bin,eggs,downloads}
install:
  - mv doodle/config/test_sample.py doodle/config/test.py
  - test -f buildout-cache/bin/buildout || python bootstrap-buildout.py -c travis.cfg
  - buildout-cache/bin/buildout -N -c travis.cfg
script:
  - buildout-cache/bin/py.test -v doodle/tests
