language: python
sudo: false
python:
  - 2.7
services:
  - redis-server
install:
  - mv doodle/config/test_sample.py doodle/config/test.py
  - pip install cython
  - pip install -r requirements.txt
  - pip install pytest
script:
  - py.test -v doodle/tests
