language: python
sudo: false
cache:
  pip: true
python:
  - 2.7
services:
  - redis-server
install:
  - mv doodle/config/test_sample.py doodle/config/test.py
  - python bootstrap-buildout.py
  - bin/buildout
script:
  - bin/test tests
