language: python
sudo: false
cache:
  pip: true
  directories:
    - bin
    - eggs
    - downloads
python:
  - 2.7
services:
  - redis-server
install:
  - mv doodle/config/test_sample.py doodle/config/test.py
  - pip install --upgrade setuptools zc.buildout --cache-dir $HOME/.cache/pip
  - buildout -N
script:
  - bin/py.test -v doodle/tests
