language: python
sudo: false
cache:
  directories:
    - bin
    - eggs
    - downloads
python:
  - 2.7
services:
  - redis-server
install:
  - mv doodle/config/test_sample.py doodle/config/test.py
  - |
    if [ ! -f bin/buildout ]; then
      wget https://bootstrap.pypa.io/bootstrap-buildout.py && python bootstrap-buildout.py
    fi
  - bin/buildout -N
script:
  - bin/py.test -v doodle/tests
