language: python
sudo: false
cache:
  pip: true
python:
  - 2.7
services:
  - redis-server
before_install:
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
install:
  - mv doodle/config/test_sample.py doodle/config/test.py
  - bin/buildout -N
script:
  - bin/py.test -v doodle/tests
