language: python
sudo: false
cache:
  pip: true
python:
  - 2.7
services:
  - redis-server
install:
  - ln -s doodle/config/test_sample.py doodle/config/test.py
  - python bootstrap-buildout.py
  - bin/buildout -N
script:
  - bin/py.test -v
